name: blood_pressure_monitor
description: A personal application for recording and visualising blood pressure and pulse readings over time
publish_to: 'none'
version: 1.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.0
  
  # SQLite with encryption
  sqflite_sqlcipher: ^2.2.1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Secure storage
  flutter_secure_storage: ^9.2.2
  
  # Authentication
  local_auth: ^2.3.0
  shared_preferences: ^2.3.3
  crypto: ^3.0.3
  
  # Utilities
  intl: ^0.18.1
  csv: ^6.0.0
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^10.1.0
  file_picker: ^8.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.4.0+1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  fake_async: ^1.3.1
  path_provider_platform_interface: ^2.1.0

  local_auth_android: any
  local_auth_darwin: any
  local_auth_windows: any
flutter:
  uses-material-design: true
